site_name: Kubernetes Notes
docs_dir: docs
theme:
  name: material
site_url: https://pages.gitlab.io/sec-robotic-process-automation/sec-rpa-opdash/opdash/
site_dir: public
markdown_extensions:
  # Admonitions - https://squidfunk.github.io/mkdocs-material/reference/admonitions/#configuration
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  # Code Blocks - https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#configuration
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  # Images - https://squidfunk.github.io/mkdocs-material/reference/images/#configuration
  - attr_list
  - md_in_html
