apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata: 
  name: ebs-sc                                        # EBS-Storage Class
provisioner: ebs.csi.aws.com                          # AWS    

# mode will delay the volume binding and provisioning of a PersistentVolume 
# until a Pod using the PersistentVolumeClaim is created.
# Ref: https://kubernetes.io/docs/concepts/storage/storage-classes/#volume-binding-mode
volumeBindingMode: WaitForFirstConsumer